# Generated by Django 4.2 on 2023-05-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_available_in_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(to='films.category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_country', to='films.country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(to='films.director'),
        ),
    ]
