-- All customers whose last name is ‘Smith’ (What will be your outcome?).
-- select *from customers where last_name = 'Smith';
-- All customers whose last name is ‘Jones’
-- select*from customers where last_name = 'Jones';
-- All customers whose firstname is not ‘Scott’.
-- select*from customers where first_name != 'Scott';