-- Fetch all of the data from the table.
-- select *from students;
-- Fetch all of the students first_names and last_names.
-- select last_name, first_name from students;
-- Fetch the student which id is equal to 2.
-- select last_name,first_name from students where id =2;
-- select last_name,first_name from students where last_name ='Benichou' and first_name ='Marc';
-- select last_name,first_name from students where last_name ='Benichou' or first_name ='Marc';
-- select last_name,first_name from students where first_name like '%a%';
-- select last_name,first_name from students where first_name like 'A%';
-- select last_name,first_name from students where first_name like '%a';
-- select last_name,first_name from students where first_name like '%a_';
-- select last_name,first_name from students where id = 1 or id = 3;
-- select * from students where birth_date >= '01/01/2000';
